option(ASSIMP_NO_EXPORT ON)
# Disable all unused importers
option(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF)
set(ASSIMP_BUILD_COLLADA_IMPORTER ON CACHE BOOL "COL IMPORTER")
set(ASSIMP_BUILD_FBX_IMPORTER     ON CACHE BOOL "FBX IMPORTER")
set(ASSIMP_BUILD_MMD_IMPORTER     ON CACHE BOOL "MMD IMPORTER")
set(ASSIMP_BUILD_OBJ_IMPORTER     ON CACHE BOOL "OBJ IMPORTER")
set(ASSIMP_BUILD_PLY_IMPORTER     ON CACHE BOOL "PLY IMPORTER")
set(ASSIMP_BUILD_STL_IMPORTER     ON CACHE BOOL "STL IMPORTER")
