set(VISCOM_OPENGL_PROFILE "4.1" CACHE STRING "OpenGL profile version to use." FORCE)
set(CMAKE_GENERATOR Ninja)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(VISCOM_CLIENTGUI OFF CACHE BOOL "Use ImGui on clients." FORCE)
set(VISCOM_SYNCINPUT OFF CACHE BOOL "Synchronize input from master to clients." FORCE)
set(VISCOM_CLIENTMOUSECURSOR OFF CACHE BOOL "Show the mouse cursor on clients." FORCE)
set(VISCOM_USE_SGCT OFF CACHE BOOL "Use SGCT for local builds.")
set(VISCOM_USE_TUIO OFF CACHE BOOL "Use TUIO input library" FORCE)
set(WITH_ERROR OFF CACHE BOOL "disable -Werror in cereal" FORCE)
set(SKIP_PORTABILITY_TEST ON CACHE BOOL "skip 32-bit test in cereal" FORCE)
set(JUST_INSTALL_CEREAL ON CACHE BOOL "skip cereal unittest sandbox and test" FORCE)

if(MSVC)
    set(ENV{SGCT_ROOT_DIR} "D:/dev/libs/SGCT-2.7.3/mscv14_x64")
endif()

if(${VISCOM_USE_SGCT})
    if(NOT MSVC)
        add_subdirectory(extern/fwcore/extern/sgct)
        include_directories(BEFORE ${PROJECT_BINARY_DIR}/extern/sgct)
    endif()
endif()
