set(VISCOM_OPENGL_PROFILE "4.1" CACHE STRING "OpenGL profile version to use." FORCE)
set(CMAKE_GENERATOR Ninja)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(VISCOM_USE_TUIO OFF CACHE BOOL "Use TUIO input library" FORCE)
set(WITH_ERROR OFF CACHE BOOL "disable -Werror in cereal" FORCE)
set(SKIP_PORTABILITY_TEST ON CACHE BOOL "skip 32-bit test in cereal" FORCE)
set(JUST_INSTALL_CEREAL ON CACHE BOOL "skip cereal unittest sandbox and test" FORCE)


#SGCT stuff.

set(VISCOM_USE_SGCT OFF CACHE BOOL "Use SGCT for local builds." FORCE)
set(VISCOM_LOCAL_ONLY ON CACHE BOOL "Only do a local build without calibration information." FORCE)
set(VISCOM_CONFIG_NAME "localms" CACHE STRING "Name/directory of the configuration files to be used (see data dir)." FORCE)
set(VISCOM_CLIENTGUI OFF CACHE BOOL "Use ImGui on clients." FORCE)
set(VISCOM_SYNCINPUT ON CACHE BOOL "Synchronize input from master to clients." FORCE)
set(VISCOM_CLIENTMOUSECURSOR OFF CACHE BOOL "Show the mouse cursor on clients." FORCE)
set(OpenGL_GL_PREFERENCE GLVND)
if(${VISCOM_USE_SGCT})
    if(MSVC)
        set(ENV{SGCT_ROOT_DIR} "D:/dev/libs/SGCT-2.7.3/mscv14_x64")
    endif()
    if(UNIX)
        set(sgct_build_dir "/home/bone/projects/viscom_framework/extern/fwcore/extern/sgct/build")
        set(ENV{SGCT_ROOT_DIR} "/home/bone/projects/viscom_framework/extern/fwcore/extern/sgct/")
        set(SGCT_DEBUG_LIBRARY "/home/bone/projects/viscom_framework/extern/fwcore/extern/sgct/build/lib/linux_x64/libsgctd.a")
        set(SGCT_RELEASE_LIBRARY "/home/bone/projects/viscom_framework/extern/fwcore/extern/sgct/build/lib/linux_x64/libsgct.a")
        set(SGCT_INCLUDE_DIRECTORY "/home/bone/projects/viscom_framework/extern/fwcore/extern/sgct/include")
    endif()
#    if(NOT MSVC)
#        add_subdirectory(extern/fwcore/extern/sgct)
#        include_directories(BEFORE ${PROJECT_BINARY_DIR}/extern/sgct)
#    endif()
else()
set(VISCOM_LOCAL_ONLY ON CACHE BOOL "Only do a local build without calibration information." FORCE)

endif()
